### ISSUE TITLE
Automate periodic pulls from upstream

### ISSUE THREAD

**Issue by limeytexan** [nixexprs/nixpkgs#2]
Up until now we have been reconciling updates from upstream using a script on account of the requirement to address merge conflicts, but would like to set up a GitHub-based automation to handle this going forward. General requirements for the automation:

* Make automation configurable with regard to the enumeration of stabilities, merge frequencies, dates, etc. It's OK to expose code as a configuration mechanism.
* Perform following steps (in this order) daily at 12pm (noon) GMT:
    * Every day, fetch updates from upstream.
    * _Before_ updating a branch, create tag of the form `<branchname>.<YYYYMMDD>`, e.g. `unstable.20220420` pointing to the current (soon to be replaced) HEAD.
    * On Monday thru Wednesday, rebase updates from `nixos-unstable` upstream into the `unstable` branch.
    * On the first Saturday of the month (or configurable), reset the `stable` branch to point to the current `staging`.
    * On Saturday, reset the `staging` branch to point to the current `unstable`.

@samrose - I'll provide you a copy of the current script offline.

A graphical representation of the workflow is shown below:
![image](https://user-images.githubusercontent.com/36448130/164206640-eb57b108-212c-4eb4-a41a-f7898814c83f.png)

**Comment by samrose** [comment]
Please do send me the script @limeytexan thank you!

**Comment by limeytexan** [comment]
> Please do send me the script @limeytexan thank you!

FTR as mentioned in spatial I dropped this off in `~sam/doit.sh` on storehouse.core.

**Comment by limeytexan** [comment]
FTR, the simple "doit" script, renamed to be a txt file: [doit.txt](https://github.com/flox/nixpkgs/files/9200549/doit.txt)
